config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # C
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  # R
  get 'tasks', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: :task

  # U
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.check_box :completed %>
    <%= f.label "Mark as Done" %>
</div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<br>
<%= link_to "Back to Homepage", tasks_path , class: 'btn btn-primary'%>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <% if task.completed %>
      <li><i class="far fa-check-circle"></i><%= link_to "  #{task.title}", task_path(task) %></li>
    <% else %>
      <li><i class="far fa-circle"></i><%= link_to "  #{task.title}", task_path(task) %></li>
    <% end %>
  <% end %>
</ul>
<%= link_to "Create New Task", tasks_new_path , class: 'btn btn-primary'%>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<br>
<%= link_to "Back to Homepage", tasks_path , class: 'btn btn-primary'%>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<br>
<h2><%= @task.details %></h2>
<br>
<% if @task.completed %>
  <p><i class="far fa-check-circle"></i><%= "  This task is completed" %></p>
  <% else %>
  <p><i class="far fa-circle"></i><%= "  This task is not completed yet" %></p>
<% end %>
<br>
<%= link_to "Edit Task!", edit_path(@task) , class: 'btn btn-primary' %>
<br>
<br>
<%= link_to "Delete Task", task_path(@task),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this task?" } , class: 'btn btn-primary' %>
<br>
<br>
<%= link_to "Back to Homepage", tasks_path , class: 'btn btn-primary' %>